from __future__ import annotations

from dataclasses import dataclass
from typing import Dict, List

from openpyxl import Workbook
from openpyxl.styles import Alignment, Border, Font, PatternFill, Side
from openpyxl.utils import get_column_letter


@dataclass(frozen=True)
class InputField:
    label: str
    name: str
    default: float | int | str
    number_format: str | None = None


HEADER_FILL = PatternFill("solid", fgColor="DCE6F1")
INPUT_FILL = PatternFill("solid", fgColor="FFF2CC")
BORDER = Border(
    left=Side(style="thin", color="D9D9D9"),
    right=Side(style="thin", color="D9D9D9"),
    top=Side(style="thin", color="D9D9D9"),
    bottom=Side(style="thin", color="D9D9D9"),
)


INPUT_FIELDS: List[InputField] = [
    InputField("Period Start Year", "Period_Start_Year", 2024, "0"),
    InputField("Projection Years", "Projection_Years", 5, "0"),
    InputField("Discount Rate", "Discount_Rate", 0.1, "0.00%"),
    InputField("Tax Rate", "Tax_Rate", 0.25, "0.00%"),
    InputField("Revenue (Base)", "Revenue_Base", 1000, "#,##0"),
    InputField("Revenue Growth Rate", "Revenue_Growth_Rate", 0.05, "0.00%"),
    InputField("EBIT Margin", "EBIT_Margin", 0.2, "0.00%"),
    InputField(
        "Depreciation % of Revenue",
        "Depreciation_Pct_Revenue",
        0.03,
        "0.00%",
    ),
    InputField("Capex % of Revenue", "Capex_Pct_Revenue", 0.04, "0.00%"),
    InputField("NWC % of Revenue", "NWC_Pct_Revenue", 0.1, "0.00%"),
    InputField("Terminal Method", "Terminal_Method", "Gordon Growth", None),
    InputField("Terminal Growth Rate", "Terminal_Growth_Rate", 0.03, "0.00%"),
    InputField("Units Outstanding", "Units_Outstanding", 100, "#,##0"),
]


DISCLAIMER_LINES = [
    "Disclaimer",
    "This model is for informational purposes only and does not constitute",
    "investment, accounting, or legal advice. Inputs are illustrative and",
    "should be reviewed and validated before use.",
    "",
    "Definitions",
    "Revenue: Top-line sales generated by the business.",
    "EBIT: Earnings before interest and taxes.",
    "NOPAT: Net operating profit after tax (EBIT after tax rate).",
    "FCF: Free cash flow to the firm (NOPAT + Depreciation - Capex - Change in NWC).",
    "NWC: Net working capital.",
]


def build_workbook() -> Workbook:
    workbook = Workbook()

    inputs_sheet = workbook.active
    inputs_sheet.title = "Inputs"
    operating_sheet = workbook.create_sheet("Operating_Model")
    valuation_sheet = workbook.create_sheet("Valuation")
    outputs_sheet = workbook.create_sheet("Outputs")
    notes_sheet = workbook.create_sheet("Notes")

    _build_inputs_sheet(inputs_sheet, workbook)
    _build_operating_sheet(operating_sheet)
    _build_valuation_sheet(valuation_sheet)
    _build_outputs_sheet(outputs_sheet)
    _build_notes_sheet(notes_sheet)
    _finalize_column_widths(
        {
            inputs_sheet: {1: 28, 2: 22},
            operating_sheet: {1: 22},
            valuation_sheet: {1: 26},
            outputs_sheet: {1: 26},
            notes_sheet: {1: 100},
        }
    )

    return workbook


def _build_inputs_sheet(sheet, workbook: Workbook) -> None:
    sheet["A1"] = "Discounted Cash Flow Inputs"
    sheet["A1"].font = Font(bold=True, size=14)

    sheet["A3"] = "Input"
    sheet["B3"] = "Value"
    for cell in (sheet["A3"], sheet["B3"]):
        cell.fill = HEADER_FILL
        cell.font = Font(bold=True)
        cell.border = BORDER
        cell.alignment = Alignment(horizontal="center")

    start_row = 4
    for idx, field in enumerate(INPUT_FIELDS, start=start_row):
        label_cell = sheet.cell(row=idx, column=1, value=field.label)
        label_cell.border = BORDER
        label_cell.alignment = Alignment(horizontal="left")

        value_cell = sheet.cell(row=idx, column=2, value=field.default)
        value_cell.fill = INPUT_FILL
        value_cell.border = BORDER
        value_cell.alignment = Alignment(horizontal="right")
        if field.number_format:
            value_cell.number_format = field.number_format

        workbook.create_named_range(field.name, sheet, value_cell.coordinate)


def _build_operating_sheet(sheet) -> None:
    sheet["A1"] = "Operating Model"
    sheet["A1"].font = Font(bold=True, size=14)

    sheet["A3"] = "Year"
    sheet["A3"].fill = HEADER_FILL
    sheet["A3"].font = Font(bold=True)
    sheet["A3"].border = BORDER

    projection_years_cell = "Projection_Years"
    start_year_cell = "Period_Start_Year"

    for offset in range(1, 11):
        col = offset + 1
        cell = sheet.cell(row=3, column=col)
        cell.value = f"=IF({offset}<={projection_years_cell},{start_year_cell}+{offset}-1,\"\")"
        cell.fill = HEADER_FILL
        cell.font = Font(bold=True)
        cell.border = BORDER
        cell.number_format = "0"

    rows = [
        (
            "Revenue",
            "=IF(B$3<>\"\",IF(B$3=$Period_Start_Year,$Revenue_Base,"
            "OFFSET(B5,0,-1)*(1+$Revenue_Growth_Rate)),\"\")",
        ),
        ("EBIT", "=IF(B$3<>\"\",B5*$EBIT_Margin,\"\")"),
        ("NOPAT", "=IF(B$3<>\"\",B6*(1-$Tax_Rate),\"\")"),
        ("Depreciation", "=IF(B$3<>\"\",B5*$Depreciation_Pct_Revenue,\"\")"),
        ("Capex", "=IF(B$3<>\"\",B5*$Capex_Pct_Revenue,\"\")"),
        ("NWC", "=IF(B$3<>\"\",B5*$NWC_Pct_Revenue,\"\")"),
        (
            "Change in NWC",
            "=IF(B$3<>\"\",IF(COLUMN()=2,B10,B10-OFFSET(B10,0,-1)),\"\")",
        ),
        (
            "FCF",
            "=IF(B$3<>\"\",B7+B8-B9-B11,\"\")",
        ),
    ]

    start_row = 5
    for idx, (label, formula) in enumerate(rows, start=start_row):
        label_cell = sheet.cell(row=idx, column=1, value=label)
        label_cell.border = BORDER
        label_cell.alignment = Alignment(horizontal="left")

        for col in range(2, 12):
            cell = sheet.cell(row=idx, column=col)
            cell.value = formula.replace("B", get_column_letter(col))
            cell.border = BORDER
            cell.number_format = "#,##0.00"


def _build_valuation_sheet(sheet) -> None:
    sheet["A1"] = "Valuation"
    sheet["A1"].font = Font(bold=True, size=14)

    headers = ["Year", "FCF", "Discount Factor", "PV of FCF"]
    for col, header in enumerate(headers, start=1):
        cell = sheet.cell(row=3, column=col, value=header)
        cell.fill = HEADER_FILL
        cell.font = Font(bold=True)
        cell.border = BORDER
        cell.alignment = Alignment(horizontal="center")

    for row in range(4, 14):
        year_cell = sheet.cell(row=row, column=1)
        year_cell.value = (
            "=IF(INDEX(Operating_Model!$B$3:$K$3,ROW()-3)<>\"\","
            "INDEX(Operating_Model!$B$3:$K$3,ROW()-3),\"\")"
        )
        year_cell.border = BORDER
        year_cell.number_format = "0"

        fcf_cell = sheet.cell(row=row, column=2)
        fcf_cell.value = (
            "=IF(INDEX(Operating_Model!$B$12:$K$12,ROW()-3)<>\"\","
            "INDEX(Operating_Model!$B$12:$K$12,ROW()-3),\"\")"
        )
        fcf_cell.border = BORDER
        fcf_cell.number_format = "#,##0.00"

        discount_cell = sheet.cell(row=row, column=3)
        discount_cell.value = (
            f"=IF(A{row}<>\"\",1/(1+$Discount_Rate)^(ROW()-3),\"\")"
        )
        discount_cell.border = BORDER
        discount_cell.number_format = "0.0000"

        pv_cell = sheet.cell(row=row, column=4)
        pv_cell.value = f"=IF(A{row}<>\"\",B{row}*C{row},\"\")"
        pv_cell.border = BORDER
        pv_cell.number_format = "#,##0.00"

    sheet["A15"] = "Terminal Value"
    sheet["B15"] = (
        "=IF($Terminal_Method=\"Gordon Growth\","
        "INDEX(B4:B13,COUNT(B4:B13))*(1+$Terminal_Growth_Rate)/"
        "($Discount_Rate-$Terminal_Growth_Rate),"
        "\"\")"
    )
    sheet["A16"] = "PV Terminal Value"
    sheet["B16"] = "=IF(B15<>\"\",B15*INDEX(C4:C13,COUNT(C4:C13)),\"\")"
    sheet["A17"] = "Enterprise Value"
    sheet["B17"] = "=IF(B16<>\"\",SUM(D4:D13)+B16,\"\")"

    for row in range(15, 18):
        for col in range(1, 3):
            cell = sheet.cell(row=row, column=col)
            cell.border = BORDER
            if col == 1:
                cell.font = Font(bold=True)
            else:
                cell.number_format = "#,##0.00"


def _build_outputs_sheet(sheet) -> None:
    sheet["A1"] = "Outputs"
    sheet["A1"].font = Font(bold=True, size=14)

    metrics = [
        ("Enterprise Value", "=Valuation!B17"),
        ("PV Explicit FCF", "=SUM(Valuation!D4:D13)"),
        ("PV Terminal", "=Valuation!B16"),
        ("Value Per Unit", "=IF($Units_Outstanding<>0,Valuation!B17/$Units_Outstanding,\"\")"),
    ]

    for row, (label, formula) in enumerate(metrics, start=3):
        sheet.cell(row=row, column=1, value=label).border = BORDER
        value_cell = sheet.cell(row=row, column=2, value=formula)
        value_cell.border = BORDER
        value_cell.number_format = "#,##0.00"

    sheet["A7"] = "Summary by Year"
    sheet["A7"].font = Font(bold=True)

    headers = ["Year", "Revenue", "EBIT", "FCF"]
    for col, header in enumerate(headers, start=1):
        cell = sheet.cell(row=8, column=col, value=header)
        cell.fill = HEADER_FILL
        cell.font = Font(bold=True)
        cell.border = BORDER
        cell.alignment = Alignment(horizontal="center")

    for row in range(9, 19):
        index_expr = "ROW()-8"
        sheet.cell(
            row=row,
            column=1,
            value=f"=IF(INDEX(Operating_Model!$B$3:$K$3,{index_expr})<>\"\","
            f"INDEX(Operating_Model!$B$3:$K$3,{index_expr}),\"\")",
        ).border = BORDER
        sheet.cell(
            row=row,
            column=2,
            value=f"=IF(INDEX(Operating_Model!$B$5:$K$5,{index_expr})<>\"\","
            f"INDEX(Operating_Model!$B$5:$K$5,{index_expr}),\"\")",
        ).border = BORDER
        sheet.cell(
            row=row,
            column=3,
            value=f"=IF(INDEX(Operating_Model!$B$6:$K$6,{index_expr})<>\"\","
            f"INDEX(Operating_Model!$B$6:$K$6,{index_expr}),\"\")",
        ).border = BORDER
        sheet.cell(
            row=row,
            column=4,
            value=f"=IF(INDEX(Operating_Model!$B$12:$K$12,{index_expr})<>\"\","
            f"INDEX(Operating_Model!$B$12:$K$12,{index_expr}),\"\")",
        ).border = BORDER
        for col in range(1, 5):
            cell = sheet.cell(row=row, column=col)
            cell.number_format = "#,##0.00" if col > 1 else "0"


def _build_notes_sheet(sheet) -> None:
    sheet["A1"] = "Notes"
    sheet["A1"].font = Font(bold=True, size=14)
    for row, line in enumerate(DISCLAIMER_LINES, start=3):
        sheet.cell(row=row, column=1, value=line)


def _finalize_column_widths(widths_by_sheet: Dict) -> None:
    for sheet, widths in widths_by_sheet.items():
        for column, width in widths.items():
            sheet.column_dimensions[get_column_letter(column)].width = width
